version: 2.1

jobs:
  build:
    docker:
      - image: nixos/nix:latest
    resource_class: large
    steps:
      - restore_cache:
          keys:
            - nix
      - checkout
      - run: nix --version
      - run: nix build --extra-experimental-features nix-command --extra-experimental-features flakes .#
      - save_cache:
          key: nix
          paths:
            - /nix
      - store_artifacts:
          path: result/bin/asciicat
          destination: asciicat-x86_64-linux

workflows:
  build-workflow:
    jobs:
      - build
