name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: decrypt shipyard token
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
        run: |
          cat "$GIT_CRYPT_KEY" | base64 -d > key-file
          git-crypt unlock key-file
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build
        run: nix build .#dockerImage
      - name: run tree
        run: tree .
      - uses: actions/upload-artifact@v4
        with:
          name: asciicat-oci.tar.gz
          path: result
